workout_tracker/forms/login.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length


class LoginForm(FlaskForm):
    username = StringField(
        'Username',
        validators=[DataRequired(), Length(min=3, max=16)]
    )
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

workout_tracker/forms/register.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import (
    DataRequired, Length, EqualTo, ValidationError, Email
)

from workout_tracker.database import Database


class RegistrationForm(FlaskForm):
    username = StringField(
        'Username', validators=[DataRequired(), Length(min=3, max=16)]
    )
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField(
        'Confirm Password', validators=[DataRequired(), EqualTo('password')]
    )
    email = StringField('Email Address', validators=[DataRequired(), Email()])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        with Database() as conn:
            query = ('SELECT user_name '
                     'FROM user_data '
                     'WHERE user_name = :username')
            user = conn.query(query, username=username.data).first()

        if user is not None:
            raise ValidationError('Oops! Someone already has that username.')

workout_tracker/forms/user.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, PasswordField
from wtforms.validators import (
    DataRequired, Length, Email
)

from workout_tracker.database import Database


def get_user_roles():
    with Database() as conn:
        query = """
        SELECT row_number() over() row_number,
               e.enumlabel user_role
        FROM pg_type t
          JOIN pg_enum e ON t.oid = e.enumtypid
          JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
        WHERE n.nspname = 'public' AND t.typname = 'role'
        ORDER BY 1"""

        return conn.query(query).all()


class UserForm(FlaskForm):
    username = StringField(
        'Username', validators=[DataRequired(), Length(min=3, max=16)]
    )
    password = PasswordField('Password', validators=[DataRequired()])
    fname = StringField('First Name', validators=[])
    lname = StringField('Last Name', validators=[])
    email = StringField('Email Address', validators=[Email()])
    user_role = SelectField(
        'Role', validators=[], choices=get_user_roles(), coerce=int,
        default=next(v[0] for v in get_user_roles() if v[1] == 'user')
    )
    city = StringField('City')
    state = StringField('State')
    submit = SubmitField('Submit')

workout_tracker/views/admin.py
from flask_bcrypt import Bcrypt
from flask_login import current_user, login_required
from flask import (
    Blueprint, flash, render_template, request, jsonify, current_app
)

from workout_tracker.database import Database
from workout_tracker.forms.user import UserForm, get_user_roles

bp = Blueprint('admin', __name__, url_prefix='/admin')


def get_users():
    query = """
    SELECT id, user_name, fname, lname, email, user_role, city, state
      FROM user_data"""

    with Database() as conn:
        return conn.query(query).all()


def get_user(user_id):
    query = """
    SELECT user_name, fname, lname, email, user_role, city, state
      FROM user_data
     WHERE id = :user_id"""

    with Database() as conn:
        return conn.query(
            query, user_id=user_id
        ).first()


def create_user(username, fname, lname, email, pw_hash,
                user_role, city, state):
    query = """
    INSERT INTO user_data (user_name, fname, lname, email, pswd,
                           user_role, city, state) VALUES
                (:username, :fname, :lname, :email, :pw_hash,
                 :user_role, :city, :state)"""

    user_role = next(
        i.user_role for i in get_user_roles() if i.row_number == user_role
    )

    with Database() as conn:
        conn.query(
            query, username=username, fname=fname, lname=lname,
            email=email, pw_hash=pw_hash, user_role=user_role,
            city=city, state=state
        )

    return True


def update_user(user_id, username, fname, lname, email, pw_hash,
                user_role, city, state):
    query = """
    UPDATE user_data
       SET user_name = :username, fname = :fname, lname = :lname,
           email = :email, pswd = :pw_hash, user_role = :user_role,
           city = :city, state = :state
     WHERE id = :user_id"""

    with Database() as conn:
        conn.query(
            query, username=username, fname=fname, lname=lname,
            email=email, pw_hash=pw_hash, user_role=user_role,
            city=city, state=state, user_id=user_id
        )

    return True


def delete_user(user_id):
    query = """DELETE FROM user_data WHERE id = :user_id"""

    with Database() as conn:
        conn.query(query, user_id=user_id)

    return True


@bp.route('/users', methods=['GET', 'POST'])
@login_required
def users():
    form = UserForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            pw_hash = Bcrypt(current_app).generate_password_hash(
                form.password.data
            ).decode('utf-8')

            create_user(username=form.username.data,
                        fname=form.fname.data,
                        lname=form.lname.data,
                        email=form.email.data,
                        pw_hash=pw_hash,
                        user_role=form.user_role.data,
                        city=form.city.data,
                        state=form.state.data)
        else:
            flash('\n'.join(form.errors), 'danger')

    return render_template('users.html', title='Manage Users',
                           users=get_users(), form=form)


@bp.route('/users/<int:user_id>', methods=['GET', 'PUT', 'DELETE'])
@login_required
def user_details(user_id):
    if request.method == 'DELETE':
        status = 200 if delete_user(user_id) else 500
        return jsonify({'status': status})
    elif request.method == 'PUT':
        pw_hash = Bcrypt(current_app).generate_password_hash(
            request.form['password']
        ).decode('utf-8')

        status = 200 if update_user(
            user_id, request.form['username'], request.form['fname'],
            request.form['lname'], request.form['email'], pw_hash,
            request.form['user_role'], request.form['city'],
            request.form['state']
        ) else 500

        return jsonify({'status': status})
    else:
        user_record = get_user(user_id)

        if not user_record:
            flash(f'User with id "{user_id}" does not exist.', 'danger')

        return render_template('user-details.html', title='User Details',
                               user=user_record, user_id=user_id)

workout_tracker/views/auth.py
from flask import (
    Blueprint, current_app, flash, redirect, render_template,
    request, url_for
)
from flask_bcrypt import Bcrypt
from flask_login import login_user, current_user, logout_user

from workout_tracker import LOGIN_MANAGER
from workout_tracker.database import Database
from workout_tracker.forms.login import LoginForm
from workout_tracker.forms.register import RegistrationForm
from workout_tracker.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


@LOGIN_MANAGER.user_loader
def load_user(user_id):
    user = User.get(int(user_id))

    if user is not None:
        return User(user.id, user.user_name, user.pswd, user.user_role)


@bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))

    form = RegistrationForm()

    if form.validate_on_submit():
        pw_hash = Bcrypt(current_app).generate_password_hash(
            form.password.data
        ).decode('utf-8')

        with Database() as conn:
            query = """
            SELECT COUNT(*) user_count
            FROM user_data
            WHERE user_name = :username OR email = :email"""

            user_count = conn.query(query, username=form.username.data,
                                    email=form.email.data).first().user_count

            print(user_count)

            if user_count > 0:
                flash('This username/email is already taken.', 'danger')
            else:
                query = """
                INSERT INTO user_data (user_name, fname, lname, email, pswd,
                                       user_role, city, state) VALUES
                            (:username, :fname, :lname, :email, :pw_hash,
                             :user_role, :city, :state)"""

                conn.query(query, username=form.username.data,
                           fname=form.fname.data, lname=form.lname.data,
                           email=form.email.data,
                           user_role='user',
                           city=form.city.data, state=form.state.data,
                           pw_hash=pw_hash)

                flash(('Your account has been created! Please log in '
                       'with your credentials to continue.'), 'success')
                return redirect(url_for('auth.login'))
    else:
        print(form.errors)

    return render_template('register.html', title='Register', form=form)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))

    form = LoginForm()

    if form.validate_on_submit():
        with Database() as conn:
            query = ('SELECT id, user_name, pswd, user_role '
                     'FROM user_data '
                     'WHERE user_name = :username')

            user_record = conn.query(
                query, username=form.username.data
            ).first()

        if user_record:
            user = User(user_id=user_record.id,
                        username=user_record.user_name,
                        pw_hash=user_record.pswd,
                        role=user_record.user_role)

            is_valid_pw = Bcrypt(current_app).check_password_hash(
                user.pw_hash, form.password.data
            )

            if user and is_valid_pw:
                login_user(user, remember=form.remember.data)

                # redirect to next page after login
                next_page = request.args.get('next')
                next_page = next_page if next_page else url_for('index')

                return redirect(next_page)
            else:
                flash('Incorrect username or password.', 'danger')
        else:
            flash('Incorrect username or password.', 'danger')

    return render_template('login.html', title='Login', form=form)


@bp.route('/logout')
def logout():
    logout_user()
    flash('You have been logged out.', 'success')

    return redirect(url_for('auth.login'))

workout_tracker/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{ title or "Exercise Tracker" }}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bulma/bulma.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
{% include "partials/navbar.html" %}
<section class="hero is-light is-fullheight-with-navbar">
    <div class="hero-body">
        <div class="container has-text-centered">
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="notification
                               {% if message[0] == 'danger' %}
                               is-danger
                               {% elif message[0] == 'success' %}
                               is-success
                               {% else %}
                               is-info
                               {% endif %}
                               ">
                            {{ message[1] }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
    </div>
    {% include "partials/footer.html" %}
</section>
{% block scripts %}
    <script src="{{ url_for('static', filename='js/vue-js/vue.js') }}"></script>
    <script src="{{ url_for("static", filename='js/main.js') }}"></script>
{% endblock %}
</body>
</html>

workout_tracker/templates/index.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

workout_tracker/templates/login.html
{# Adapted from https://dansup.github.io/bulma-templates/templates/login.html #}
{% extends "base.html" %}

{% block content %}
    <div class="column is-4 is-offset-4">
        <h3 class="title has-text-grey">Login</h3>
        <p class="subtitle has-text-grey">Please login to proceed.</p>
        <div class="box">
            <form method="post" action="{{ url_for('auth.login', next=request.args.get('next')) }}">
                {{ form.hidden_tag() }}

                <div class="field">
                    <div class="control">
                        {{ form.username.label() }}
                        {% if form.username.errors %}
                            {{ form.username(class="input is-large is-danger") }}
                            {% for error in form.username.errors %}
                                <span class="has-text-danger">{{ error }}</span>
                            {% endfor %}
                        {% else %}
                            {{ form.username(class="input is-large", placeholder='Your Username') }}
                        {% endif %}
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        {{ form.password.label() }}
                        {% if form.password.errors %}
                            {{ form.password(class="input is-large is-danger") }}
                            {% for error in form.password.errors %}
                                <span class="has-text-danger">{{ error }}</span>
                            {% endfor %}
                        {% else %}
                            {{ form.password(class="input is-large", placeholder='Your Password') }}
                        {% endif %}
                    </div>
                </div>

                <div class="field">
                    {% if form.remember.errors %}
                        {{ form.remember(class="is-danger") }}
                        {{ form.remember.label(class='checkbox') }}
                        {% for error in form.remember.errors %}
                            <span class="has-text-danger">{{ error }}</span>
                        {% endfor %}
                    {% else %}
                        {{ form.remember() }}
                        {{ form.remember.label(class='checkbox') }}
                    {% endif %}
                </div>

                <div class="field">
                    {{ form.submit(class='button is-block is-info is-large is-fullwidth') }}
                </div>
            </form>
        </div>
        <p class="has-text-grey">
            <a href="{{ url_for('auth.register') }}">Register</a> &nbsp;·&nbsp;
            <a href="{{ url_for('index') }}">Forgot Password</a>
        </p>
    </div>
{% endblock %}

workout_tracker/templates/register.html
{# Adapted from https://dansup.github.io/bulma-templates/templates/login.html #}
{% extends "base.html" %}

{% block content %}
    <div class="column is-4 is-offset-4">
        <h3 class="title has-text-grey">Register</h3>
        <p class="subtitle has-text-grey">Please complete the sign up process.</p>
        <div class="box">
            <form method="post" action="{{ url_for('auth.register', next=request.args.get('next')) }}">
                {{ form.hidden_tag() }}

                <div class="field">
                    <div class="control">
                        {{ form.username.label() }}
                        {% if form.username.errors %}
                            {{ form.username(class="input is-large is-danger") }}
                            {% for error in form.username.errors %}
                                <span class="has-text-danger">{{ error }}</span>
                            {% endfor %}
                        {% else %}
                            {{ form.username(class="input is-large", placeholder='Your Username') }}
                        {% endif %}
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        {{ form.email.label() }}
                        {% if form.email.errors %}
                            {{ form.email(class="input is-large is-danger") }}
                            {% for error in form.email.errors %}
                                <span class="has-text-danger">{{ error }}</span>
                            {% endfor %}
                        {% else %}
                            {{ form.email(class="input is-large", placeholder='Your Email') }}
                        {% endif %}
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        {{ form.password.label() }}
                        {% if form.password.errors %}
                            {{ form.password(class="input is-large is-danger") }}
                            {% for error in form.password.errors %}
                                <span class="has-text-danger">{{ error }}</span>
                            {% endfor %}
                        {% else %}
                            {{ form.password(class="input is-large", placeholder='Your Password') }}
                        {% endif %}
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        {{ form.confirm_password.label() }}
                        {% if form.confirm_password.errors %}
                            {{ form.confirm_password(class="input is-large is-danger") }}
                            {% for error in form.confirm_password.errors %}
                                <span class="has-text-danger">{{ error }}</span>
                            {% endfor %}
                        {% else %}
                            {{ form.confirm_password(class="input is-large", placeholder='Confirm Password') }}
                        {% endif %}
                    </div>
                </div>

                <div class="field">
                    {{ form.submit(class='button is-block is-info is-large is-fullwidth') }}
                </div>
            </form>
        </div>
        <p class="has-text-grey">
            <a href="{{ url_for('auth.register') }}">Register</a> &nbsp;·&nbsp;
            <a href="{{ url_for('index') }}">Forgot Password</a>
        </p>
    </div>
{% endblock %}

workout_tracker/templates/user-details.html
{% extends "base.html" %}

{% block content %}
    <nav class="breadcrumb">
        <ul>
            <li>
                <a href="{{ url_for('admin.users') }}">Users</a>
            </li>
            <li class="is-active">
                <a href="{{ url_for('admin.user_details', user_id=user_id) }}">{{ user_id }}</a>
            </li>
        </ul>
    </nav>
    {% if user is not none %}
        <div class="card">
            <header class="card-header">
                <p class="card-header-title">User Details</p>
            </header>
            <div class="card-content">
                <div class="content">
                    <p><strong>user_name:</strong> {{ user.user_name or "" }}</p>
                    <p><strong>fname:</strong> {{ user.fname or "" }}</p>
                    <p><strong>lname:</strong> {{ user.lname or "" }}</p>
                    <p><strong>email:</strong> {{ user.email or "" }}</p>
                    <p><strong>user_role:</strong> {{ user.user_role or "" }}</p>
                    <p><strong>city:</strong> {{ user.city or "" }}</p>
                    <p><strong>state:</strong> {{ user.state or "" }}</p>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block scripts %}
{% endblock %}

workout_tracker/templates/users.html
{% extends "base.html" %}

{% block content %}
    <div class="columns">
        <div class="column">
            <h3 class="is-size-4 heading">Create User</h3>
            <div class="box">
                <form method="post" action="{{ url_for('admin.users') }}">
                    {{ form.hidden_tag() }}
                    <div class="field">
                        <div class="control">
                            {{ form.username.label() }}
                            {% if form.username.errors %}
                                {{ form.username(class="input is-danger") }}
                                {% for error in form.username.errors %}
                                    <span class="has-text-danger">{{ error }}</span>
                                {% endfor %}
                            {% else %}
                                {{ form.username(class="input", placeholder='Username') }}
                            {% endif %}
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            {{ form.password.label() }}
                            {% if form.password.errors %}
                                {{ form.password(class="input is-danger") }}
                                {% for error in form.password.errors %}
                                    <span class="has-text-danger">{{ error }}</span>
                                {% endfor %}
                            {% else %}
                                {{ form.password(class="input", placeholder='Password') }}
                            {% endif %}
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            {{ form.fname.label() }}
                            {% if form.fname.errors %}
                                {{ form.fname(class="input is-danger") }}
                                {% for error in form.fname.errors %}
                                    <span class="has-text-danger">{{ error }}</span>
                                {% endfor %}
                            {% else %}
                                {{ form.fname(class="input", placeholder='First Name') }}
                            {% endif %}
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            {{ form.lname.label() }}
                            {% if form.lname.errors %}
                                {{ form.lname(class="input is-danger") }}
                                {% for error in form.lname.errors %}
                                    <span class="has-text-danger">{{ error }}</span>
                                {% endfor %}
                            {% else %}
                                {{ form.lname(class="input", placeholder='Last Name') }}
                            {% endif %}
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            {{ form.email.label() }}
                            {% if form.email.errors %}
                                {{ form.email(class="input is-danger") }}
                                {% for error in form.email.errors %}
                                    <span class="has-text-danger">{{ error }}</span>
                                {% endfor %}
                            {% else %}
                                {{ form.email(class="input", placeholder='Email') }}
                            {% endif %}
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            {{ form.user_role.label() }}
                            {% if form.user_role.errors %}
                                <div class="select is-danger">
                                    {{ form.user_role() }}
                                </div>
                                {% for error in form.user_role.errors %}
                                    <span class="has-text-danger">{{ error }}</span>
                                {% endfor %}
                            {% else %}
                                <div class="select">
                                    {{ form.user_role() }}
                                </div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            {{ form.city.label() }}
                            {% if form.city.errors %}
                                {{ form.city(class="input is-danger") }}
                                {% for error in form.city.errors %}
                                    <span class="has-text-danger">{{ error }}</span>
                                {% endfor %}
                            {% else %}
                                {{ form.city(class="input", placeholder='City') }}
                            {% endif %}
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            {{ form.state.label() }}
                            {% if form.state.errors %}
                                {{ form.state(class="input is-danger") }}
                                {% for error in form.state.errors %}
                                    <span class="has-text-danger">{{ error }}</span>
                                {% endfor %}
                            {% else %}
                                {{ form.state(class="input", placeholder='State') }}
                            {% endif %}
                        </div>
                    </div>

                    <div class="field">
                        {{ form.submit(class='button is-block is-info is-fullwidth') }}
                    </div>

                </form>
            </div>
        </div>
        <div class="column">
            <h3 class="is-size-4 heading">List of Users</h3>
            <table class="table">
                <thead>
                <tr>
                    <th>user_name</th>
                    <th>fname</th>
                    <th>lname</th>
                    <th>email</th>
                    <th>user_role</th>
                    <th>city</th>
                    <th>state</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                        <td>
                            <a class="has-text-link"
                               href="{{ url_for('admin.user_details', user_id=user.id) }}">
                                {{ user.user_name or "" }}
                            </a>
                        </td>
                        <td>{{ user.fname or "" }}</td>
                        <td>{{ user.lname or "" }}</td>
                        <td>{{ user.email or "" }}</td>
                        <td>{{ user.user_role or "" }}</td>
                        <td>{{ user.city or "" }}</td>
                        <td>{{ user.state or "" }}</td>
                        <td>
                            <button class="button is-primary is-small">Edit</button>
                        </td>
                        <td>
                            <button class="button is-danger is-small">Delete</button>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}