workout_tracker/views/admin.py
from flask_bcrypt import Bcrypt
from flask_login import current_user, login_required
from flask import (
    Blueprint, flash, render_template, request, jsonify, current_app
)

from workout_tracker.database import Database
from workout_tracker.forms.user import UserForm, get_user_roles

bp = Blueprint('admin', __name__, url_prefix='/admin')


def get_users():
    query = """
    SELECT id, user_name, fname, lname, email, user_role, city, state
      FROM user_data"""

    with Database() as conn:
        return conn.query(query).all()


def get_user(user_id):
    query = """
    SELECT user_name, fname, lname, email, user_role, city, state
      FROM user_data
     WHERE id = :user_id"""

    with Database() as conn:
        return conn.query(
            query, user_id=user_id
        ).first()


def create_user(username, fname, lname, email, pw_hash,
                user_role, city, state):
    query = """
    INSERT INTO user_data (user_name, fname, lname, email, pswd,
                           user_role, city, state) VALUES
                (:username, :fname, :lname, :email, :pw_hash,
                 :user_role, :city, :state)"""

    user_role = next(
        i.user_role for i in get_user_roles() if i.row_number == user_role
    )

    with Database() as conn:
        conn.query(
            query, username=username, fname=fname, lname=lname,
            email=email, pw_hash=pw_hash, user_role=user_role,
            city=city, state=state
        )

    return True


def update_user(user_id, username, fname, lname, email, pw_hash,
                user_role, city, state):
    query = """
    UPDATE user_data
       SET user_name = :username, fname = :fname, lname = :lname,
           email = :email, pswd = :pw_hash, user_role = :user_role,
           city = :city, state = :state
     WHERE id = :user_id"""

    with Database() as conn:
        conn.query(
            query, username=username, fname=fname, lname=lname,
            email=email, pw_hash=pw_hash, user_role=user_role,
            city=city, state=state, user_id=user_id
        )

    return True


def delete_user(user_id):
    query = """DELETE FROM user_data WHERE id = :user_id"""

    with Database() as conn:
        conn.query(query, user_id=user_id)

    return True


@bp.route('/users', methods=['GET', 'POST'])
@login_required
def users():
    form = UserForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            pw_hash = Bcrypt(current_app).generate_password_hash(
                form.password.data
            ).decode('utf-8')

            create_user(username=form.username.data,
                        fname=form.fname.data,
                        lname=form.lname.data,
                        email=form.email.data,
                        pw_hash=pw_hash,
                        user_role=form.user_role.data,
                        city=form.city.data,
                        state=form.state.data)
        else:
            flash('\n'.join(form.errors), 'danger')

    return render_template('users.html', title='Manage Users',
                           users=get_users(), form=form)


@bp.route('/users/<int:user_id>', methods=['GET', 'PUT', 'DELETE'])
@login_required
def user_details(user_id):
    if request.method == 'DELETE':
        status = 200 if delete_user(user_id) else 500
        return jsonify({'status': status})
    elif request.method == 'PUT':
        pw_hash = Bcrypt(current_app).generate_password_hash(
            request.form['password']
        ).decode('utf-8')

        status = 200 if update_user(
            user_id, request.form['username'], request.form['fname'],
            request.form['lname'], request.form['email'], pw_hash,
            request.form['user_role'], request.form['city'],
            request.form['state']
        ) else 500

        return jsonify({'status': status})
    else:
        user_record = get_user(user_id)

        if not user_record:
            flash(f'User with id "{user_id}" does not exist.', 'danger')

        return render_template('user-details.html', title='User Details',
                               user=user_record, user_id=user_id)

workout_tracker/views/auth.py
from flask import (
    Blueprint, current_app, flash, redirect, render_template,
    request, url_for
)
from flask_bcrypt import Bcrypt
from flask_login import login_user, current_user, logout_user

from workout_tracker import LOGIN_MANAGER
from workout_tracker.database import Database
from workout_tracker.forms.login import LoginForm
from workout_tracker.forms.register import RegistrationForm
from workout_tracker.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


@LOGIN_MANAGER.user_loader
def load_user(user_id):
    user = User.get(int(user_id))

    if user is not None:
        return User(user.id, user.user_name, user.pswd, user.user_role)


@bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))

    form = RegistrationForm()

    if form.validate_on_submit():
        pw_hash = Bcrypt(current_app).generate_password_hash(
            form.password.data
        ).decode('utf-8')

        with Database() as conn:
            query = """
            SELECT COUNT(*) user_count
            FROM user_data
            WHERE user_name = :username OR email = :email"""

            user_count = conn.query(query, username=form.username.data,
                                    email=form.email.data).first().user_count

            print(user_count)

            if user_count > 0:
                flash('This username/email is already taken.', 'danger')
            else:
                query = """
                INSERT INTO user_data (user_name, fname, lname, email, pswd,
                                       user_role, city, state) VALUES
                            (:username, :fname, :lname, :email, :pw_hash,
                             :user_role, :city, :state)"""

                conn.query(query, username=form.username.data,
                           fname=form.fname.data, lname=form.lname.data,
                           email=form.email.data,
                           user_role='user',
                           city=form.city.data, state=form.state.data,
                           pw_hash=pw_hash)

                flash(('Your account has been created! Please log in '
                       'with your credentials to continue.'), 'success')
                return redirect(url_for('auth.login'))
    else:
        print(form.errors)

    return render_template('register.html', title='Register', form=form)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))

    form = LoginForm()

    if form.validate_on_submit():
        with Database() as conn:
            query = ('SELECT id, user_name, pswd, user_role '
                     'FROM user_data '
                     'WHERE user_name = :username')

            user_record = conn.query(
                query, username=form.username.data
            ).first()

        if user_record:
            user = User(user_id=user_record.id,
                        username=user_record.user_name,
                        pw_hash=user_record.pswd,
                        role=user_record.user_role)

            is_valid_pw = Bcrypt(current_app).check_password_hash(
                user.pw_hash, form.password.data
            )

            if user and is_valid_pw:
                login_user(user, remember=form.remember.data)

                # redirect to next page after login
                next_page = request.args.get('next')
                next_page = next_page if next_page else url_for('index')

                return redirect(next_page)
            else:
                flash('Incorrect username or password.', 'danger')
        else:
            flash('Incorrect username or password.', 'danger')

    return render_template('login.html', title='Login', form=form)


@bp.route('/logout')
def logout():
    logout_user()
    flash('You have been logged out.', 'success')

    return redirect(url_for('auth.login'))

workout_tracker/templates/partials/footer.html
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Exercise Tracker</strong>
        &copy; 2019
    </p>
  </div>
</footer>

workout_tracker/templates/partials/navbar.html
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{{ url_for('index') }}">
            <img src="{{ url_for('static', filename='img/headerlogo.png') }}" width="112" height="28">
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
           data-target="navbar">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id='navbar' class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href="{{ url_for('index') }}">Home</a>
            {% if current_user.username and current_user.role == 'admin' %}
                <a class="navbar-item">SQL Runner</a>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Manage</a>
                    <div class="navbar-dropdown">
                        <a class="navbar-item", href="{{ url_for('admin.users') }}">Users</a>
                    </div>
                </div>
            {% endif %}
        </div>

        <div class="navbar-end">
            <div class="navbar-item">
                {% if current_user.username %}
                    <div class="buttons">
                        <a class="button is-light" href="{{ url_for('auth.logout') }}">Log out</a>
                    </div>
                {% else %}
                    <div class="buttons">
                        <a class="button is-primary" href="{{ url_for('auth.register') }}">
                            <strong>Register</strong>
                        </a>
                        <a class="button is-light" href="{{ url_for('auth.login') }}">Log in</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>